.NET driver can't create records in multi-master replicated database
jpamp/OrientDB-NET.binary pull request #3
Opened 2017-03-08 23:36 UTC by SamHard

This change solves the issue of "Local node 'Node1' is not the owner for cluster 'v' (it is 'Node2')" when hosting a database on more than one server with multi-master replication. (JIRA SM-248)  This solution was identified by Colin Leister from OrientDB.

2017-03-09 15:45 UTC, jpamp requested changes
Just have the one comment.  Can you address?

2017-03-09 15:45 UTC, jpamp commented on src/OrientDB-Net.binary.Innov8tive/Protocol/Operations/RecordCreate.cs
>                  var clusterId = _database.GetClusterIdFor(_document.OClassName);
Do we still need this line if we are not using the value anymore?

2017-03-09 16:12 UTC, SamHard commented on src/OrientDB-Net.binary.Innov8tive/Protocol/Operations/RecordCreate.cs
>                  var clusterId = _database.GetClusterIdFor(_document.OClassName);
No, that is not needed.  Thanks!

2017-03-10 15:44 UTC, jpamp approved these changes

2017-03-10 15:45 UTC, merged